### ISSUE TITLE
Error occurred when running the CI tool at this point: Object type Class: deleting Email OAuth credentials

### ISSUE THREAD

**Issue by Clink50** [Kentico/xperience-training-13#106]
### Brief bug description

What went wrong?
I ran `ContinuousIntegration.exe -r` and it makes it to the point where it attempts to delete the Email OAuth credentials and fails. 

### Repro steps

1. Clone the xperience-training-13 
2. Copy from the cloned repo `\CMS\App_Data\CIRepository` to `medioclinic\CMS\App_Data\CIRepository`. 
3. Run the `ContinuousIntegration.exe -r` tool
4. Once it reaches the `Object type Class: deleting Email OAuth credentials`, it fails.

### Test environment

 - Platform/OS: Windows, .NET 6.0
 - Browser: Command Prompt
 - Version: 13.0 Hotfix 83

### Additional context

Object type Class: deleting Email OAuth credentials
Message: Restoration of object type "Class" failed during objects' deletion. See inner exception for further details.

Exception type: CMS.ContinuousIntegration.ObjectTypeSerializationException
Stack trace:
   at CMS.ContinuousIntegration.Internal.FileSystemRestoreAllJob.TryRun(Action\`2 method, String objectType, CancellationToken cancellationToken, String exceptionMessageFormat)
   at CMS.ContinuousIntegration.Internal.FileSystemRestoreAllJob.<>c__DisplayClass12_0.<DeleteAndDisposeObjects>b__0(String objectType)
   at CMS.ContinuousIntegration.Internal.AbstractFileSystemJob.CancellableForEach[T](CancellationToken cancellationToken, IEnumerable\`1 collection, Action\`2 action)
   at CMS.ContinuousIntegration.Internal.AbstractFileSystemJob.CancellableForEach[T](CancellationToken cancellationToken, IEnumerable\`1 collection, Action\`1 action)
   at CMS.ContinuousIntegration.Internal.FileSystemRestoreAllJob.DeleteAndDisposeObjects(IEnumerable\`1 orderedObjectTypes, CancellationToken cancellationToken)
   at CMS.ContinuousIntegration.Internal.FileSystemRestoreAllJob.RunInternal(CancellationToken cancellationToken)
   at CMS.ContinuousIntegration.Internal.AbstractFileSystemAllJob.Run(Nullable\`1 cancellationToken)

Message: Deletion of object type "Class" (cms.class) failed for object "Email OAuth credentials" (ClassID: 5529). See inner exception for further details.

Exception type: CMS.ContinuousIntegration.ObjectTypeSerializationException
Stack trace:
   at CMS.ContinuousIntegration.Internal.FileSystemDeleteObjectsByTypeJob.DeleteObjectBase(String objectType, BaseInfo info, ISet\`1 mainFilesLocations, String logMessageFormat, Queue\`1 notDeletedObjects)
   at CMS.ContinuousIntegration.Internal.FileSystemDeleteObjectsByTypeJob.<>c__DisplayClass2_0.<ProcessDeletedObjects>b__1(BaseInfo info)
   at CMS.ContinuousIntegration.Internal.AbstractFileSystemJob.CancellableForEach[T](CancellationToken cancellationToken, IEnumerable\`1 collection, Action\`2 action)
   at CMS.ContinuousIntegration.Internal.AbstractFileSystemJob.CancellableForEach[T](CancellationToken cancellationToken, IEnumerable\`1 collection, Action\`1 action)
   at CMS.ContinuousIntegration.Internal.FileSystemDeleteObjectsByTypeJob.ProcessDeletedObjects(String objectType, ISet\`1 repositoryLocations, CancellationToken cancellationToken)
   at CMS.ContinuousIntegration.Internal.FileSystemDeleteObjectsByTypeJob.RunInternal(String objectType, ISet\`1 fileLocations, CancellationToken cancellationToken)
   at CMS.ContinuousIntegration.Internal.AbstractFileSystemTypeWideJob.Run(String objectType, ISet\`1 fileLocations, Nullable\`1 cancellationToken)
   at CMS.ContinuousIntegration.Internal.FileSystemRestoreObjectsByTypeInternalJob.RunDeleteObjectsByTypeJob()
   at CMS.ContinuousIntegration.Internal.FileSystemRestoreAllJob.DeleteAndDispose(String objectType, CancellationToken cancellationToken)
   at CMS.ContinuousIntegration.Internal.FileSystemRestoreAllJob.TryRun(Action\`2 method, String objectType, CancellationToken cancellationToken, String exceptionMessageFormat)

Message: You first need to delete the corresponding code (Info, Provider) and recompile the solution.

Exception type: System.InvalidOperationException
Stack trace:
   at CMS.DataEngine.DataClassInfoProvider.DeleteInfo(DataClassInfo info)
   at CMS.DataEngine.BaseInfo.Delete()
   at CMS.ContinuousIntegration.Internal.FileSystemDeleteObjectsByTypeJob.DeleteObject(BaseInfo obj, RepositoryLocationsCollection objectLocations, ISet\`1 repositoryLocations, String logMessageFormat)
   at CMS.ContinuousIntegration.Internal.FileSystemDeleteObjectsByTypeJob.DeleteObjectBase(String objectType, BaseInfo info, ISet\`1 mainFilesLocations, String logMessageFormat, Queue\`1 notDeletedObjects)

Errors occurred while restoring objects from the repository:
Message: Restoration of object type "Class" failed during objects' deletion. See inner exception for further details.

Exception type: CMS.ContinuousIntegration.ObjectTypeSerializationException
Stack trace:
   at CMS.ContinuousIntegration.Internal.FileSystemRestoreAllJob.TryRun(Action\`2 method, String objectType, CancellationToken cancellationToken, String exceptionMessageFormat)
   at CMS.ContinuousIntegration.Internal.FileSystemRestoreAllJob.<>c__DisplayClass12_0.<DeleteAndDisposeObjects>b__0(String objectType)
   at CMS.ContinuousIntegration.Internal.AbstractFileSystemJob.CancellableForEach[T](CancellationToken cancellationToken, IEnumerable\`1 collection, Action\`2 action)
   at CMS.ContinuousIntegration.Internal.AbstractFileSystemJob.CancellableForEach[T](CancellationToken cancellationToken, IEnumerable\`1 collection, Action\`1 action)
   at CMS.ContinuousIntegration.Internal.FileSystemRestoreAllJob.DeleteAndDisposeObjects(IEnumerable\`1 orderedObjectTypes, CancellationToken cancellationToken)
   at CMS.ContinuousIntegration.Internal.FileSystemRestoreAllJob.RunInternal(CancellationToken cancellationToken)
   at CMS.ContinuousIntegration.Internal.AbstractFileSystemAllJob.Run(Nullable\`1 cancellationToken)

Message: Deletion of object type "Class" (cms.class) failed for object "Email OAuth credentials" (ClassID: 5529). See inner exception for further details.

Exception type: CMS.ContinuousIntegration.ObjectTypeSerializationException
Stack trace:
   at CMS.ContinuousIntegration.Internal.FileSystemDeleteObjectsByTypeJob.DeleteObjectBase(String objectType, BaseInfo info, ISet\`1 mainFilesLocations, String logMessageFormat, Queue\`1 notDeletedObjects)
   at CMS.ContinuousIntegration.Internal.FileSystemDeleteObjectsByTypeJob.<>c__DisplayClass2_0.<ProcessDeletedObjects>b__1(BaseInfo info)
   at CMS.ContinuousIntegration.Internal.AbstractFileSystemJob.CancellableForEach[T](CancellationToken cancellationToken, IEnumerable\`1 collection, Action\`2 action)
   at CMS.ContinuousIntegration.Internal.AbstractFileSystemJob.CancellableForEach[T](CancellationToken cancellationToken, IEnumerable\`1 collection, Action\`1 action)
   at CMS.ContinuousIntegration.Internal.FileSystemDeleteObjectsByTypeJob.ProcessDeletedObjects(String objectType, ISet\`1 repositoryLocations, CancellationToken cancellationToken)
   at CMS.ContinuousIntegration.Internal.FileSystemDeleteObjectsByTypeJob.RunInternal(String objectType, ISet\`1 fileLocations, CancellationToken cancellationToken)
   at CMS.ContinuousIntegration.Internal.AbstractFileSystemTypeWideJob.Run(String objectType, ISet\`1 fileLocations, Nullable\`1 cancellationToken)
   at CMS.ContinuousIntegration.Internal.FileSystemRestoreObjectsByTypeInternalJob.RunDeleteObjectsByTypeJob()
   at CMS.ContinuousIntegration.Internal.FileSystemRestoreAllJob.DeleteAndDispose(String objectType, CancellationToken cancellationToken)
   at CMS.ContinuousIntegration.Internal.FileSystemRestoreAllJob.TryRun(Action\`2 method, String objectType, CancellationToken cancellationToken, String exceptionMessageFormat)

Message: You first need to delete the corresponding code (Info, Provider) and recompile the solution.

Exception type: System.InvalidOperationException
Stack trace:
   at CMS.DataEngine.DataClassInfoProvider.DeleteInfo(DataClassInfo info)
   at CMS.DataEngine.BaseInfo.Delete()
   at CMS.ContinuousIntegration.Internal.FileSystemDeleteObjectsByTypeJob.DeleteObject(BaseInfo obj, RepositoryLocationsCollection objectLocations, ISet\`1 repositoryLocations, String logMessageFormat)
   at CMS.ContinuousIntegration.Internal.FileSystemDeleteObjectsByTypeJob.DeleteObjectBase(String objectType, BaseInfo info, ISet\`1 mainFilesLocations, String logMessageFormat, Queue\`1 notDeletedObjects)

**Comment by JanLenoch** [comment]
Hi @Clink50 ,

I'm sorry to hear about that. BTW, thanks for a great error report! By looking at your hotfix level, I figured out that there must have been an obsolete instruction in the course contents saying that you need to install Xperience 13 Refresh 4. I recently made an update in the GitHub repo that also pertains to the hotfix level. Unfortunately, the obsolete instruction in the course slipped through the radar and that is almost certainly the culprit of your error. Please install [Xperience 13 Refresh 7](https://download.kentico.com/Xperience_13_Refresh7_trial.exe) and try again.

Please let me know if that helped or not.

Thanks.

**Comment by Clink50** [comment]
Hey @JanLenoch, no problem! Unfortunately, we are using [Xperience 13 Refresh 7]https://download.kentico.com/Xperience_13_Refresh7_trial.exe) not Refresh 4, however we have hotfix 83 installed. Do we need to upgrade to a later hotfix for this issue to be resolved?

**Comment by JanLenoch** [comment]
Ahh, true, the 83 hotfix is indeed Refresh 7. Nevertheless, this is strange since this error occurs when you have a code base that's aware of the email OAuth object type but no data thereof in the database. Can you verify that you have the CMS_EmailOAuthCredentials table in the database, with a respective record in the CMS_Class table?

**Comment by Clink50** [comment]
I do have a CMS_EmailOAuthCredentials table in the database, but there are no records in that table. I checked in the CMS_Class table and I do see a record for the email OAuth credentials. Here are some of the values that looked useful, but let me know if there is something else I can provide.

ClassID = 5529
ClassDisplayName = "Email OAuth credentials" 
ClassName = "CMS.EmailOAuthCredentials"
ClassTableName = "CMS_EmailOAuthCredentials"

**Comment by JanLenoch** [comment]
Hi @Clink50 , sorry for the delay. I just found the root cause. I'll commit the fix soon in the [xp-for-developers-essentials](https://github.com/Kentico/xperience-training-13/tree/xp-for-developers-essentials) branch. The commit will be linked to this issue. Please let me know if that works for you.

**Comment by JanLenoch** [comment]
@Clink50 Also, if you happen to be working on other modules than Essentials, I'll fix that in the others too.

**Comment by Clink50** [comment]
@JanLenoch Sorry for the late response. Thank you, this fixed the issue and it is working as expected now!
